/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.compras.ide;

import org.xtext.example.compras.ide.AbstractComprasIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ComprasIdeModule extends AbstractComprasIdeModule {
}
