/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.compras.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.compras.ComprasRuntimeModule;
import org.xtext.example.compras.ComprasStandaloneSetup;
import org.xtext.example.compras.ide.ComprasIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ComprasIdeSetup extends ComprasStandaloneSetup {
  @Override
  public Injector createInjector() {
    ComprasRuntimeModule _comprasRuntimeModule = new ComprasRuntimeModule();
    ComprasIdeModule _comprasIdeModule = new ComprasIdeModule();
    return Guice.createInjector(Modules2.mixin(_comprasRuntimeModule, _comprasIdeModule));
  }
}
