/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.compras.compras.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.compras.compras.Architecture;
import org.xtext.example.compras.compras.BusinessLayer;
import org.xtext.example.compras.compras.BusinessLayerRef;
import org.xtext.example.compras.compras.CommonFieldType;
import org.xtext.example.compras.compras.CommonLayer;
import org.xtext.example.compras.compras.CommonLayerRef;
import org.xtext.example.compras.compras.ComprasFactory;
import org.xtext.example.compras.compras.ComprasPackage;
import org.xtext.example.compras.compras.ControllerSegmentLayer;
import org.xtext.example.compras.compras.ControllersRef;
import org.xtext.example.compras.compras.DataAccessLayer;
import org.xtext.example.compras.compras.DataAccessLayerRef;
import org.xtext.example.compras.compras.DatabaseRDBMSType;
import org.xtext.example.compras.compras.DbConnectorSegmentLayer;
import org.xtext.example.compras.compras.Domain;
import org.xtext.example.compras.compras.Entity;
import org.xtext.example.compras.compras.EntityField;
import org.xtext.example.compras.compras.EntityFieldLabel;
import org.xtext.example.compras.compras.EntityFieldRequired;
import org.xtext.example.compras.compras.EntityType;
import org.xtext.example.compras.compras.FuncCreateAction;
import org.xtext.example.compras.compras.FuncDeleteAction;
import org.xtext.example.compras.compras.FuncEditAction;
import org.xtext.example.compras.compras.FuncViewDropDownAction;
import org.xtext.example.compras.compras.FuncViewGridAction;
import org.xtext.example.compras.compras.Functionality;
import org.xtext.example.compras.compras.FunctionalityActionType;
import org.xtext.example.compras.compras.ModuleTech;
import org.xtext.example.compras.compras.PresentationLayer;
import org.xtext.example.compras.compras.Relations;
import org.xtext.example.compras.compras.RelationsType;
import org.xtext.example.compras.compras.ScriptRef;
import org.xtext.example.compras.compras.ScriptSegmentLayer;
import org.xtext.example.compras.compras.Solution;
import org.xtext.example.compras.compras.Technology;
import org.xtext.example.compras.compras.ViewSegmentLayer;
import org.xtext.example.compras.compras.ViewsRef;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ComprasPackageImpl extends EPackageImpl implements ComprasPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass solutionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass domainEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass moduleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityFieldLabelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityFieldRequiredEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass functionalityEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass functionalityActionTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass funcCreateActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass funcViewGridActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass funcViewDropDownActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass funcEditActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass funcDeleteActionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass architectureEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass presentationLayerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass controllerSegmentLayerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass viewSegmentLayerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass scriptSegmentLayerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass businessLayerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dataAccessLayerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dbConnectorSegmentLayerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass commonLayerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass relationsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass technologyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass moduleTechEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass controllersRefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass viewsRefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass scriptRefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass businessLayerRefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dataAccessLayerRefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass commonLayerRefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum commonFieldTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum relationsTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum databaseRDBMSTypeEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.compras.compras.ComprasPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private ComprasPackageImpl()
  {
    super(eNS_URI, ComprasFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link ComprasPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static ComprasPackage init()
  {
    if (isInited) return (ComprasPackage)EPackage.Registry.INSTANCE.getEPackage(ComprasPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredComprasPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    ComprasPackageImpl theComprasPackage = registeredComprasPackage instanceof ComprasPackageImpl ? (ComprasPackageImpl)registeredComprasPackage : new ComprasPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theComprasPackage.createPackageContents();

    // Initialize created meta-data
    theComprasPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theComprasPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(ComprasPackage.eNS_URI, theComprasPackage);
    return theComprasPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSolution()
  {
    return solutionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSolution_Name()
  {
    return (EAttribute)solutionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSolution_Domain()
  {
    return (EReference)solutionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSolution_Architecture()
  {
    return (EReference)solutionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSolution_Technology()
  {
    return (EReference)solutionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDomain()
  {
    return domainEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDomain_Module()
  {
    return (EReference)domainEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModule()
  {
    return moduleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getModule_Name()
  {
    return (EAttribute)moduleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModule_Entity()
  {
    return (EReference)moduleEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModule_Functionality()
  {
    return (EReference)moduleEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEntity()
  {
    return entityEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEntity_Name()
  {
    return (EAttribute)entityEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEntity_EntityField()
  {
    return (EReference)entityEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEntityField()
  {
    return entityFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEntityField_EntityFieldRequired()
  {
    return (EReference)entityFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEntityField_EntityFieldLabel()
  {
    return (EReference)entityFieldEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEntityField_EntityType()
  {
    return (EReference)entityFieldEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEntityField_Name()
  {
    return (EAttribute)entityFieldEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEntityFieldLabel()
  {
    return entityFieldLabelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEntityFieldLabel_Name()
  {
    return (EAttribute)entityFieldLabelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEntityFieldRequired()
  {
    return entityFieldRequiredEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEntityFieldRequired_Name()
  {
    return (EAttribute)entityFieldRequiredEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEntityType()
  {
    return entityTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEntityType_Entity()
  {
    return (EReference)entityTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEntityType_CommonFieldType()
  {
    return (EAttribute)entityTypeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFunctionality()
  {
    return functionalityEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFunctionality_Name()
  {
    return (EAttribute)functionalityEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFunctionality_Entity()
  {
    return (EReference)functionalityEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFunctionality_FunctionalityActionType()
  {
    return (EReference)functionalityEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFunctionalityActionType()
  {
    return functionalityActionTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFunctionalityActionType_Name()
  {
    return (EAttribute)functionalityActionTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFuncCreateAction()
  {
    return funcCreateActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFuncViewGridAction()
  {
    return funcViewGridActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFuncViewDropDownAction()
  {
    return funcViewDropDownActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFuncEditAction()
  {
    return funcEditActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFuncDeleteAction()
  {
    return funcDeleteActionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getArchitecture()
  {
    return architectureEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getArchitecture_PresentationLayer()
  {
    return (EReference)architectureEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getArchitecture_BusinessLayer()
  {
    return (EReference)architectureEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getArchitecture_DataAccessLayer()
  {
    return (EReference)architectureEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getArchitecture_CommonLayer()
  {
    return (EReference)architectureEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getArchitecture_Relations()
  {
    return (EReference)architectureEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPresentationLayer()
  {
    return presentationLayerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPresentationLayer_Name()
  {
    return (EAttribute)presentationLayerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPresentationLayer_ControllerSegmentLayer()
  {
    return (EReference)presentationLayerEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPresentationLayer_ViewSegmentLayer()
  {
    return (EReference)presentationLayerEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPresentationLayer_ScriptegmentLayer()
  {
    return (EReference)presentationLayerEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getControllerSegmentLayer()
  {
    return controllerSegmentLayerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getControllerSegmentLayer_Name()
  {
    return (EAttribute)controllerSegmentLayerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getViewSegmentLayer()
  {
    return viewSegmentLayerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getViewSegmentLayer_Name()
  {
    return (EAttribute)viewSegmentLayerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getScriptSegmentLayer()
  {
    return scriptSegmentLayerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getScriptSegmentLayer_Name()
  {
    return (EAttribute)scriptSegmentLayerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBusinessLayer()
  {
    return businessLayerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBusinessLayer_Name()
  {
    return (EAttribute)businessLayerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDataAccessLayer()
  {
    return dataAccessLayerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDataAccessLayer_Name()
  {
    return (EAttribute)dataAccessLayerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDataAccessLayer_DbConnectorSegmentLayer()
  {
    return (EReference)dataAccessLayerEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDbConnectorSegmentLayer()
  {
    return dbConnectorSegmentLayerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDbConnectorSegmentLayer_Name()
  {
    return (EAttribute)dbConnectorSegmentLayerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCommonLayer()
  {
    return commonLayerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCommonLayer_Name()
  {
    return (EAttribute)commonLayerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRelations()
  {
    return relationsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRelations_SourceLayer1()
  {
    return (EReference)relationsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRelations_RelationsType1()
  {
    return (EAttribute)relationsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRelations_TargetLayer1()
  {
    return (EReference)relationsEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRelations_SourceLayer2()
  {
    return (EReference)relationsEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRelations_RelationsType2()
  {
    return (EAttribute)relationsEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRelations_TargetLayer2()
  {
    return (EReference)relationsEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRelations_SourceLayer3()
  {
    return (EReference)relationsEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRelations_RelationsType3()
  {
    return (EAttribute)relationsEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRelations_TargetLayer3()
  {
    return (EReference)relationsEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRelations_SourceLayer4()
  {
    return (EReference)relationsEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRelations_RelationsType4()
  {
    return (EAttribute)relationsEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRelations_TargetLayer4()
  {
    return (EReference)relationsEClass.getEStructuralFeatures().get(11);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRelations_SourceLayer5()
  {
    return (EReference)relationsEClass.getEStructuralFeatures().get(12);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRelations_RelationsType5()
  {
    return (EAttribute)relationsEClass.getEStructuralFeatures().get(13);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRelations_TargetLayer5()
  {
    return (EReference)relationsEClass.getEStructuralFeatures().get(14);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTechnology()
  {
    return technologyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTechnology_ModuleTech()
  {
    return (EReference)technologyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTechnology_DbConnectorSegmentLayer()
  {
    return (EReference)technologyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTechnology_DatabaseRDBMSType()
  {
    return (EAttribute)technologyEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTechnology_ConnectionString()
  {
    return (EAttribute)technologyEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModuleTech()
  {
    return moduleTechEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModuleTech_Name()
  {
    return (EReference)moduleTechEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModuleTech_PresentationLayer()
  {
    return (EReference)moduleTechEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModuleTech_ControllerSegmentLayer()
  {
    return (EReference)moduleTechEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModuleTech_ControllersRef()
  {
    return (EReference)moduleTechEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModuleTech_ViewSegmentLayer()
  {
    return (EReference)moduleTechEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModuleTech_ViewsRef()
  {
    return (EReference)moduleTechEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModuleTech_ScriptSegmentLayer()
  {
    return (EReference)moduleTechEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModuleTech_ScriptRef()
  {
    return (EReference)moduleTechEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModuleTech_BusinessLayer()
  {
    return (EReference)moduleTechEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModuleTech_BusinessLayerRef()
  {
    return (EReference)moduleTechEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModuleTech_DataAccessLayer()
  {
    return (EReference)moduleTechEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModuleTech_DataAccessLayerRef()
  {
    return (EReference)moduleTechEClass.getEStructuralFeatures().get(11);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModuleTech_CommonLayer()
  {
    return (EReference)moduleTechEClass.getEStructuralFeatures().get(12);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModuleTech_CommonLayerRef()
  {
    return (EReference)moduleTechEClass.getEStructuralFeatures().get(13);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getControllersRef()
  {
    return controllersRefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getControllersRef_Functionality()
  {
    return (EReference)controllersRefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getViewsRef()
  {
    return viewsRefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getViewsRef_Functionality()
  {
    return (EReference)viewsRefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getScriptRef()
  {
    return scriptRefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getScriptRef_Functionality()
  {
    return (EReference)scriptRefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBusinessLayerRef()
  {
    return businessLayerRefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getBusinessLayerRef_Functionality()
  {
    return (EReference)businessLayerRefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDataAccessLayerRef()
  {
    return dataAccessLayerRefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDataAccessLayerRef_Functionality()
  {
    return (EReference)dataAccessLayerRefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCommonLayerRef()
  {
    return commonLayerRefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCommonLayerRef_Entity()
  {
    return (EReference)commonLayerRefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getCommonFieldType()
  {
    return commonFieldTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getRelationsType()
  {
    return relationsTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getDatabaseRDBMSType()
  {
    return databaseRDBMSTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComprasFactory getComprasFactory()
  {
    return (ComprasFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    solutionEClass = createEClass(SOLUTION);
    createEAttribute(solutionEClass, SOLUTION__NAME);
    createEReference(solutionEClass, SOLUTION__DOMAIN);
    createEReference(solutionEClass, SOLUTION__ARCHITECTURE);
    createEReference(solutionEClass, SOLUTION__TECHNOLOGY);

    domainEClass = createEClass(DOMAIN);
    createEReference(domainEClass, DOMAIN__MODULE);

    moduleEClass = createEClass(MODULE);
    createEAttribute(moduleEClass, MODULE__NAME);
    createEReference(moduleEClass, MODULE__ENTITY);
    createEReference(moduleEClass, MODULE__FUNCTIONALITY);

    entityEClass = createEClass(ENTITY);
    createEAttribute(entityEClass, ENTITY__NAME);
    createEReference(entityEClass, ENTITY__ENTITY_FIELD);

    entityFieldEClass = createEClass(ENTITY_FIELD);
    createEReference(entityFieldEClass, ENTITY_FIELD__ENTITY_FIELD_REQUIRED);
    createEReference(entityFieldEClass, ENTITY_FIELD__ENTITY_FIELD_LABEL);
    createEReference(entityFieldEClass, ENTITY_FIELD__ENTITY_TYPE);
    createEAttribute(entityFieldEClass, ENTITY_FIELD__NAME);

    entityFieldLabelEClass = createEClass(ENTITY_FIELD_LABEL);
    createEAttribute(entityFieldLabelEClass, ENTITY_FIELD_LABEL__NAME);

    entityFieldRequiredEClass = createEClass(ENTITY_FIELD_REQUIRED);
    createEAttribute(entityFieldRequiredEClass, ENTITY_FIELD_REQUIRED__NAME);

    entityTypeEClass = createEClass(ENTITY_TYPE);
    createEReference(entityTypeEClass, ENTITY_TYPE__ENTITY);
    createEAttribute(entityTypeEClass, ENTITY_TYPE__COMMON_FIELD_TYPE);

    functionalityEClass = createEClass(FUNCTIONALITY);
    createEAttribute(functionalityEClass, FUNCTIONALITY__NAME);
    createEReference(functionalityEClass, FUNCTIONALITY__ENTITY);
    createEReference(functionalityEClass, FUNCTIONALITY__FUNCTIONALITY_ACTION_TYPE);

    functionalityActionTypeEClass = createEClass(FUNCTIONALITY_ACTION_TYPE);
    createEAttribute(functionalityActionTypeEClass, FUNCTIONALITY_ACTION_TYPE__NAME);

    funcCreateActionEClass = createEClass(FUNC_CREATE_ACTION);

    funcViewGridActionEClass = createEClass(FUNC_VIEW_GRID_ACTION);

    funcViewDropDownActionEClass = createEClass(FUNC_VIEW_DROP_DOWN_ACTION);

    funcEditActionEClass = createEClass(FUNC_EDIT_ACTION);

    funcDeleteActionEClass = createEClass(FUNC_DELETE_ACTION);

    architectureEClass = createEClass(ARCHITECTURE);
    createEReference(architectureEClass, ARCHITECTURE__PRESENTATION_LAYER);
    createEReference(architectureEClass, ARCHITECTURE__BUSINESS_LAYER);
    createEReference(architectureEClass, ARCHITECTURE__DATA_ACCESS_LAYER);
    createEReference(architectureEClass, ARCHITECTURE__COMMON_LAYER);
    createEReference(architectureEClass, ARCHITECTURE__RELATIONS);

    presentationLayerEClass = createEClass(PRESENTATION_LAYER);
    createEAttribute(presentationLayerEClass, PRESENTATION_LAYER__NAME);
    createEReference(presentationLayerEClass, PRESENTATION_LAYER__CONTROLLER_SEGMENT_LAYER);
    createEReference(presentationLayerEClass, PRESENTATION_LAYER__VIEW_SEGMENT_LAYER);
    createEReference(presentationLayerEClass, PRESENTATION_LAYER__SCRIPTEGMENT_LAYER);

    controllerSegmentLayerEClass = createEClass(CONTROLLER_SEGMENT_LAYER);
    createEAttribute(controllerSegmentLayerEClass, CONTROLLER_SEGMENT_LAYER__NAME);

    viewSegmentLayerEClass = createEClass(VIEW_SEGMENT_LAYER);
    createEAttribute(viewSegmentLayerEClass, VIEW_SEGMENT_LAYER__NAME);

    scriptSegmentLayerEClass = createEClass(SCRIPT_SEGMENT_LAYER);
    createEAttribute(scriptSegmentLayerEClass, SCRIPT_SEGMENT_LAYER__NAME);

    businessLayerEClass = createEClass(BUSINESS_LAYER);
    createEAttribute(businessLayerEClass, BUSINESS_LAYER__NAME);

    dataAccessLayerEClass = createEClass(DATA_ACCESS_LAYER);
    createEAttribute(dataAccessLayerEClass, DATA_ACCESS_LAYER__NAME);
    createEReference(dataAccessLayerEClass, DATA_ACCESS_LAYER__DB_CONNECTOR_SEGMENT_LAYER);

    dbConnectorSegmentLayerEClass = createEClass(DB_CONNECTOR_SEGMENT_LAYER);
    createEAttribute(dbConnectorSegmentLayerEClass, DB_CONNECTOR_SEGMENT_LAYER__NAME);

    commonLayerEClass = createEClass(COMMON_LAYER);
    createEAttribute(commonLayerEClass, COMMON_LAYER__NAME);

    relationsEClass = createEClass(RELATIONS);
    createEReference(relationsEClass, RELATIONS__SOURCE_LAYER1);
    createEAttribute(relationsEClass, RELATIONS__RELATIONS_TYPE1);
    createEReference(relationsEClass, RELATIONS__TARGET_LAYER1);
    createEReference(relationsEClass, RELATIONS__SOURCE_LAYER2);
    createEAttribute(relationsEClass, RELATIONS__RELATIONS_TYPE2);
    createEReference(relationsEClass, RELATIONS__TARGET_LAYER2);
    createEReference(relationsEClass, RELATIONS__SOURCE_LAYER3);
    createEAttribute(relationsEClass, RELATIONS__RELATIONS_TYPE3);
    createEReference(relationsEClass, RELATIONS__TARGET_LAYER3);
    createEReference(relationsEClass, RELATIONS__SOURCE_LAYER4);
    createEAttribute(relationsEClass, RELATIONS__RELATIONS_TYPE4);
    createEReference(relationsEClass, RELATIONS__TARGET_LAYER4);
    createEReference(relationsEClass, RELATIONS__SOURCE_LAYER5);
    createEAttribute(relationsEClass, RELATIONS__RELATIONS_TYPE5);
    createEReference(relationsEClass, RELATIONS__TARGET_LAYER5);

    technologyEClass = createEClass(TECHNOLOGY);
    createEReference(technologyEClass, TECHNOLOGY__MODULE_TECH);
    createEReference(technologyEClass, TECHNOLOGY__DB_CONNECTOR_SEGMENT_LAYER);
    createEAttribute(technologyEClass, TECHNOLOGY__DATABASE_RDBMS_TYPE);
    createEAttribute(technologyEClass, TECHNOLOGY__CONNECTION_STRING);

    moduleTechEClass = createEClass(MODULE_TECH);
    createEReference(moduleTechEClass, MODULE_TECH__NAME);
    createEReference(moduleTechEClass, MODULE_TECH__PRESENTATION_LAYER);
    createEReference(moduleTechEClass, MODULE_TECH__CONTROLLER_SEGMENT_LAYER);
    createEReference(moduleTechEClass, MODULE_TECH__CONTROLLERS_REF);
    createEReference(moduleTechEClass, MODULE_TECH__VIEW_SEGMENT_LAYER);
    createEReference(moduleTechEClass, MODULE_TECH__VIEWS_REF);
    createEReference(moduleTechEClass, MODULE_TECH__SCRIPT_SEGMENT_LAYER);
    createEReference(moduleTechEClass, MODULE_TECH__SCRIPT_REF);
    createEReference(moduleTechEClass, MODULE_TECH__BUSINESS_LAYER);
    createEReference(moduleTechEClass, MODULE_TECH__BUSINESS_LAYER_REF);
    createEReference(moduleTechEClass, MODULE_TECH__DATA_ACCESS_LAYER);
    createEReference(moduleTechEClass, MODULE_TECH__DATA_ACCESS_LAYER_REF);
    createEReference(moduleTechEClass, MODULE_TECH__COMMON_LAYER);
    createEReference(moduleTechEClass, MODULE_TECH__COMMON_LAYER_REF);

    controllersRefEClass = createEClass(CONTROLLERS_REF);
    createEReference(controllersRefEClass, CONTROLLERS_REF__FUNCTIONALITY);

    viewsRefEClass = createEClass(VIEWS_REF);
    createEReference(viewsRefEClass, VIEWS_REF__FUNCTIONALITY);

    scriptRefEClass = createEClass(SCRIPT_REF);
    createEReference(scriptRefEClass, SCRIPT_REF__FUNCTIONALITY);

    businessLayerRefEClass = createEClass(BUSINESS_LAYER_REF);
    createEReference(businessLayerRefEClass, BUSINESS_LAYER_REF__FUNCTIONALITY);

    dataAccessLayerRefEClass = createEClass(DATA_ACCESS_LAYER_REF);
    createEReference(dataAccessLayerRefEClass, DATA_ACCESS_LAYER_REF__FUNCTIONALITY);

    commonLayerRefEClass = createEClass(COMMON_LAYER_REF);
    createEReference(commonLayerRefEClass, COMMON_LAYER_REF__ENTITY);

    // Create enums
    commonFieldTypeEEnum = createEEnum(COMMON_FIELD_TYPE);
    relationsTypeEEnum = createEEnum(RELATIONS_TYPE);
    databaseRDBMSTypeEEnum = createEEnum(DATABASE_RDBMS_TYPE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    funcCreateActionEClass.getESuperTypes().add(this.getFunctionalityActionType());
    funcViewGridActionEClass.getESuperTypes().add(this.getFunctionalityActionType());
    funcViewDropDownActionEClass.getESuperTypes().add(this.getFunctionalityActionType());
    funcEditActionEClass.getESuperTypes().add(this.getFunctionalityActionType());
    funcDeleteActionEClass.getESuperTypes().add(this.getFunctionalityActionType());

    // Initialize classes and features; add operations and parameters
    initEClass(solutionEClass, Solution.class, "Solution", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSolution_Name(), ecorePackage.getEString(), "name", null, 0, 1, Solution.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSolution_Domain(), this.getDomain(), null, "domain", null, 0, 1, Solution.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSolution_Architecture(), this.getArchitecture(), null, "architecture", null, 0, 1, Solution.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSolution_Technology(), this.getTechnology(), null, "technology", null, 0, 1, Solution.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(domainEClass, Domain.class, "Domain", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDomain_Module(), this.getModule(), null, "module", null, 0, -1, Domain.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(moduleEClass, org.xtext.example.compras.compras.Module.class, "Module", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getModule_Name(), ecorePackage.getEString(), "name", null, 0, 1, org.xtext.example.compras.compras.Module.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModule_Entity(), this.getEntity(), null, "entity", null, 0, -1, org.xtext.example.compras.compras.Module.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModule_Functionality(), this.getFunctionality(), null, "functionality", null, 0, -1, org.xtext.example.compras.compras.Module.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityEClass, Entity.class, "Entity", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEntity_Name(), ecorePackage.getEString(), "name", null, 0, 1, Entity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntity_EntityField(), this.getEntityField(), null, "entityField", null, 0, -1, Entity.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityFieldEClass, EntityField.class, "EntityField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityField_EntityFieldRequired(), this.getEntityFieldRequired(), null, "entityFieldRequired", null, 0, 1, EntityField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityField_EntityFieldLabel(), this.getEntityFieldLabel(), null, "entityFieldLabel", null, 0, 1, EntityField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEntityField_EntityType(), this.getEntityType(), null, "entityType", null, 0, 1, EntityField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEntityField_Name(), ecorePackage.getEString(), "name", null, 0, 1, EntityField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityFieldLabelEClass, EntityFieldLabel.class, "EntityFieldLabel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEntityFieldLabel_Name(), ecorePackage.getEString(), "name", null, 0, 1, EntityFieldLabel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityFieldRequiredEClass, EntityFieldRequired.class, "EntityFieldRequired", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEntityFieldRequired_Name(), ecorePackage.getEString(), "name", null, 0, 1, EntityFieldRequired.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityTypeEClass, EntityType.class, "EntityType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEntityType_Entity(), this.getEntity(), null, "entity", null, 0, 1, EntityType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEntityType_CommonFieldType(), this.getCommonFieldType(), "commonFieldType", null, 0, 1, EntityType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(functionalityEClass, Functionality.class, "Functionality", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFunctionality_Name(), ecorePackage.getEString(), "name", null, 0, 1, Functionality.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFunctionality_Entity(), this.getEntity(), null, "entity", null, 0, 1, Functionality.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFunctionality_FunctionalityActionType(), this.getFunctionalityActionType(), null, "functionalityActionType", null, 0, -1, Functionality.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(functionalityActionTypeEClass, FunctionalityActionType.class, "FunctionalityActionType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFunctionalityActionType_Name(), ecorePackage.getEString(), "name", null, 0, 1, FunctionalityActionType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(funcCreateActionEClass, FuncCreateAction.class, "FuncCreateAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(funcViewGridActionEClass, FuncViewGridAction.class, "FuncViewGridAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(funcViewDropDownActionEClass, FuncViewDropDownAction.class, "FuncViewDropDownAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(funcEditActionEClass, FuncEditAction.class, "FuncEditAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(funcDeleteActionEClass, FuncDeleteAction.class, "FuncDeleteAction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(architectureEClass, Architecture.class, "Architecture", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getArchitecture_PresentationLayer(), this.getPresentationLayer(), null, "presentationLayer", null, 0, 1, Architecture.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getArchitecture_BusinessLayer(), this.getBusinessLayer(), null, "businessLayer", null, 0, 1, Architecture.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getArchitecture_DataAccessLayer(), this.getDataAccessLayer(), null, "dataAccessLayer", null, 0, 1, Architecture.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getArchitecture_CommonLayer(), this.getCommonLayer(), null, "commonLayer", null, 0, 1, Architecture.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getArchitecture_Relations(), this.getRelations(), null, "relations", null, 0, 1, Architecture.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(presentationLayerEClass, PresentationLayer.class, "PresentationLayer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPresentationLayer_Name(), ecorePackage.getEString(), "name", null, 0, 1, PresentationLayer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPresentationLayer_ControllerSegmentLayer(), this.getControllerSegmentLayer(), null, "controllerSegmentLayer", null, 0, 1, PresentationLayer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPresentationLayer_ViewSegmentLayer(), this.getViewSegmentLayer(), null, "viewSegmentLayer", null, 0, 1, PresentationLayer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPresentationLayer_ScriptegmentLayer(), this.getScriptSegmentLayer(), null, "scriptegmentLayer", null, 0, 1, PresentationLayer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(controllerSegmentLayerEClass, ControllerSegmentLayer.class, "ControllerSegmentLayer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getControllerSegmentLayer_Name(), ecorePackage.getEString(), "name", null, 0, 1, ControllerSegmentLayer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(viewSegmentLayerEClass, ViewSegmentLayer.class, "ViewSegmentLayer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getViewSegmentLayer_Name(), ecorePackage.getEString(), "name", null, 0, 1, ViewSegmentLayer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(scriptSegmentLayerEClass, ScriptSegmentLayer.class, "ScriptSegmentLayer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getScriptSegmentLayer_Name(), ecorePackage.getEString(), "name", null, 0, 1, ScriptSegmentLayer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(businessLayerEClass, BusinessLayer.class, "BusinessLayer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBusinessLayer_Name(), ecorePackage.getEString(), "name", null, 0, 1, BusinessLayer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dataAccessLayerEClass, DataAccessLayer.class, "DataAccessLayer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDataAccessLayer_Name(), ecorePackage.getEString(), "name", null, 0, 1, DataAccessLayer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDataAccessLayer_DbConnectorSegmentLayer(), this.getDbConnectorSegmentLayer(), null, "dbConnectorSegmentLayer", null, 0, 1, DataAccessLayer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dbConnectorSegmentLayerEClass, DbConnectorSegmentLayer.class, "DbConnectorSegmentLayer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDbConnectorSegmentLayer_Name(), ecorePackage.getEString(), "name", null, 0, 1, DbConnectorSegmentLayer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(commonLayerEClass, CommonLayer.class, "CommonLayer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCommonLayer_Name(), ecorePackage.getEString(), "name", null, 0, 1, CommonLayer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(relationsEClass, Relations.class, "Relations", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRelations_SourceLayer1(), this.getPresentationLayer(), null, "sourceLayer1", null, 0, 1, Relations.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRelations_RelationsType1(), this.getRelationsType(), "relationsType1", null, 0, 1, Relations.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRelations_TargetLayer1(), this.getBusinessLayer(), null, "targetLayer1", null, 0, 1, Relations.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRelations_SourceLayer2(), this.getBusinessLayer(), null, "sourceLayer2", null, 0, 1, Relations.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRelations_RelationsType2(), this.getRelationsType(), "relationsType2", null, 0, 1, Relations.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRelations_TargetLayer2(), this.getDataAccessLayer(), null, "targetLayer2", null, 0, 1, Relations.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRelations_SourceLayer3(), this.getDataAccessLayer(), null, "sourceLayer3", null, 0, 1, Relations.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRelations_RelationsType3(), this.getRelationsType(), "relationsType3", null, 0, 1, Relations.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRelations_TargetLayer3(), this.getCommonLayer(), null, "targetLayer3", null, 0, 1, Relations.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRelations_SourceLayer4(), this.getPresentationLayer(), null, "sourceLayer4", null, 0, 1, Relations.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRelations_RelationsType4(), this.getRelationsType(), "relationsType4", null, 0, 1, Relations.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRelations_TargetLayer4(), this.getCommonLayer(), null, "targetLayer4", null, 0, 1, Relations.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRelations_SourceLayer5(), this.getBusinessLayer(), null, "sourceLayer5", null, 0, 1, Relations.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRelations_RelationsType5(), this.getRelationsType(), "relationsType5", null, 0, 1, Relations.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRelations_TargetLayer5(), this.getCommonLayer(), null, "targetLayer5", null, 0, 1, Relations.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(technologyEClass, Technology.class, "Technology", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTechnology_ModuleTech(), this.getModuleTech(), null, "moduleTech", null, 0, -1, Technology.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTechnology_DbConnectorSegmentLayer(), this.getDbConnectorSegmentLayer(), null, "dbConnectorSegmentLayer", null, 0, 1, Technology.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTechnology_DatabaseRDBMSType(), this.getDatabaseRDBMSType(), "databaseRDBMSType", null, 0, 1, Technology.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTechnology_ConnectionString(), ecorePackage.getEString(), "connectionString", null, 0, 1, Technology.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(moduleTechEClass, ModuleTech.class, "ModuleTech", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModuleTech_Name(), this.getModule(), null, "name", null, 0, 1, ModuleTech.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModuleTech_PresentationLayer(), this.getPresentationLayer(), null, "presentationLayer", null, 0, 1, ModuleTech.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModuleTech_ControllerSegmentLayer(), this.getControllerSegmentLayer(), null, "controllerSegmentLayer", null, 0, 1, ModuleTech.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModuleTech_ControllersRef(), this.getControllersRef(), null, "controllersRef", null, 0, -1, ModuleTech.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModuleTech_ViewSegmentLayer(), this.getViewSegmentLayer(), null, "viewSegmentLayer", null, 0, 1, ModuleTech.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModuleTech_ViewsRef(), this.getViewsRef(), null, "viewsRef", null, 0, -1, ModuleTech.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModuleTech_ScriptSegmentLayer(), this.getScriptSegmentLayer(), null, "scriptSegmentLayer", null, 0, 1, ModuleTech.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModuleTech_ScriptRef(), this.getScriptRef(), null, "scriptRef", null, 0, -1, ModuleTech.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModuleTech_BusinessLayer(), this.getBusinessLayer(), null, "businessLayer", null, 0, 1, ModuleTech.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModuleTech_BusinessLayerRef(), this.getBusinessLayerRef(), null, "businessLayerRef", null, 0, -1, ModuleTech.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModuleTech_DataAccessLayer(), this.getDataAccessLayer(), null, "dataAccessLayer", null, 0, 1, ModuleTech.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModuleTech_DataAccessLayerRef(), this.getDataAccessLayerRef(), null, "dataAccessLayerRef", null, 0, -1, ModuleTech.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModuleTech_CommonLayer(), this.getCommonLayer(), null, "commonLayer", null, 0, 1, ModuleTech.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModuleTech_CommonLayerRef(), this.getCommonLayerRef(), null, "commonLayerRef", null, 0, -1, ModuleTech.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(controllersRefEClass, ControllersRef.class, "ControllersRef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getControllersRef_Functionality(), this.getFunctionality(), null, "functionality", null, 0, 1, ControllersRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(viewsRefEClass, ViewsRef.class, "ViewsRef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getViewsRef_Functionality(), this.getFunctionality(), null, "functionality", null, 0, 1, ViewsRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(scriptRefEClass, ScriptRef.class, "ScriptRef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getScriptRef_Functionality(), this.getFunctionality(), null, "functionality", null, 0, 1, ScriptRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(businessLayerRefEClass, BusinessLayerRef.class, "BusinessLayerRef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getBusinessLayerRef_Functionality(), this.getFunctionality(), null, "functionality", null, 0, 1, BusinessLayerRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dataAccessLayerRefEClass, DataAccessLayerRef.class, "DataAccessLayerRef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDataAccessLayerRef_Functionality(), this.getFunctionality(), null, "functionality", null, 0, 1, DataAccessLayerRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(commonLayerRefEClass, CommonLayerRef.class, "CommonLayerRef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCommonLayerRef_Entity(), this.getEntity(), null, "entity", null, 0, 1, CommonLayerRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(commonFieldTypeEEnum, CommonFieldType.class, "CommonFieldType");
    addEEnumLiteral(commonFieldTypeEEnum, CommonFieldType.STRING);
    addEEnumLiteral(commonFieldTypeEEnum, CommonFieldType.INT);
    addEEnumLiteral(commonFieldTypeEEnum, CommonFieldType.BOOL);
    addEEnumLiteral(commonFieldTypeEEnum, CommonFieldType.FLOAT);
    addEEnumLiteral(commonFieldTypeEEnum, CommonFieldType.DATE);

    initEEnum(relationsTypeEEnum, RelationsType.class, "RelationsType");
    addEEnumLiteral(relationsTypeEEnum, RelationsType.ALLOWED_TO_USE);

    initEEnum(databaseRDBMSTypeEEnum, DatabaseRDBMSType.class, "DatabaseRDBMSType");
    addEEnumLiteral(databaseRDBMSTypeEEnum, DatabaseRDBMSType.SQLSERVER);
    addEEnumLiteral(databaseRDBMSTypeEEnum, DatabaseRDBMSType.ORACLE);
    addEEnumLiteral(databaseRDBMSTypeEEnum, DatabaseRDBMSType.POSTGRES);

    // Create resource
    createResource(eNS_URI);
  }

} //ComprasPackageImpl
