/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.compras.compras.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.compras.compras.ComprasPackage;
import org.xtext.example.compras.compras.DataAccessLayer;
import org.xtext.example.compras.compras.DbConnectorSegmentLayer;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data Access Layer</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.compras.compras.impl.DataAccessLayerImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.DataAccessLayerImpl#getDbConnectorSegmentLayer <em>Db Connector Segment Layer</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DataAccessLayerImpl extends MinimalEObjectImpl.Container implements DataAccessLayer
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getDbConnectorSegmentLayer() <em>Db Connector Segment Layer</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDbConnectorSegmentLayer()
   * @generated
   * @ordered
   */
  protected DbConnectorSegmentLayer dbConnectorSegmentLayer;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DataAccessLayerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ComprasPackage.Literals.DATA_ACCESS_LAYER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.DATA_ACCESS_LAYER__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DbConnectorSegmentLayer getDbConnectorSegmentLayer()
  {
    return dbConnectorSegmentLayer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDbConnectorSegmentLayer(DbConnectorSegmentLayer newDbConnectorSegmentLayer, NotificationChain msgs)
  {
    DbConnectorSegmentLayer oldDbConnectorSegmentLayer = dbConnectorSegmentLayer;
    dbConnectorSegmentLayer = newDbConnectorSegmentLayer;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ComprasPackage.DATA_ACCESS_LAYER__DB_CONNECTOR_SEGMENT_LAYER, oldDbConnectorSegmentLayer, newDbConnectorSegmentLayer);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDbConnectorSegmentLayer(DbConnectorSegmentLayer newDbConnectorSegmentLayer)
  {
    if (newDbConnectorSegmentLayer != dbConnectorSegmentLayer)
    {
      NotificationChain msgs = null;
      if (dbConnectorSegmentLayer != null)
        msgs = ((InternalEObject)dbConnectorSegmentLayer).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ComprasPackage.DATA_ACCESS_LAYER__DB_CONNECTOR_SEGMENT_LAYER, null, msgs);
      if (newDbConnectorSegmentLayer != null)
        msgs = ((InternalEObject)newDbConnectorSegmentLayer).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ComprasPackage.DATA_ACCESS_LAYER__DB_CONNECTOR_SEGMENT_LAYER, null, msgs);
      msgs = basicSetDbConnectorSegmentLayer(newDbConnectorSegmentLayer, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.DATA_ACCESS_LAYER__DB_CONNECTOR_SEGMENT_LAYER, newDbConnectorSegmentLayer, newDbConnectorSegmentLayer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ComprasPackage.DATA_ACCESS_LAYER__DB_CONNECTOR_SEGMENT_LAYER:
        return basicSetDbConnectorSegmentLayer(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ComprasPackage.DATA_ACCESS_LAYER__NAME:
        return getName();
      case ComprasPackage.DATA_ACCESS_LAYER__DB_CONNECTOR_SEGMENT_LAYER:
        return getDbConnectorSegmentLayer();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ComprasPackage.DATA_ACCESS_LAYER__NAME:
        setName((String)newValue);
        return;
      case ComprasPackage.DATA_ACCESS_LAYER__DB_CONNECTOR_SEGMENT_LAYER:
        setDbConnectorSegmentLayer((DbConnectorSegmentLayer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ComprasPackage.DATA_ACCESS_LAYER__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ComprasPackage.DATA_ACCESS_LAYER__DB_CONNECTOR_SEGMENT_LAYER:
        setDbConnectorSegmentLayer((DbConnectorSegmentLayer)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ComprasPackage.DATA_ACCESS_LAYER__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ComprasPackage.DATA_ACCESS_LAYER__DB_CONNECTOR_SEGMENT_LAYER:
        return dbConnectorSegmentLayer != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //DataAccessLayerImpl
