/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.compras.compras.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.compras.compras.CommonFieldType;
import org.xtext.example.compras.compras.ComprasPackage;
import org.xtext.example.compras.compras.Entity;
import org.xtext.example.compras.compras.EntityType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Entity Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.compras.compras.impl.EntityTypeImpl#getEntity <em>Entity</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.EntityTypeImpl#getCommonFieldType <em>Common Field Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EntityTypeImpl extends MinimalEObjectImpl.Container implements EntityType
{
  /**
   * The cached value of the '{@link #getEntity() <em>Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntity()
   * @generated
   * @ordered
   */
  protected Entity entity;

  /**
   * The default value of the '{@link #getCommonFieldType() <em>Common Field Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCommonFieldType()
   * @generated
   * @ordered
   */
  protected static final CommonFieldType COMMON_FIELD_TYPE_EDEFAULT = CommonFieldType.STRING;

  /**
   * The cached value of the '{@link #getCommonFieldType() <em>Common Field Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCommonFieldType()
   * @generated
   * @ordered
   */
  protected CommonFieldType commonFieldType = COMMON_FIELD_TYPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EntityTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ComprasPackage.Literals.ENTITY_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Entity getEntity()
  {
    if (entity != null && entity.eIsProxy())
    {
      InternalEObject oldEntity = (InternalEObject)entity;
      entity = (Entity)eResolveProxy(oldEntity);
      if (entity != oldEntity)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ComprasPackage.ENTITY_TYPE__ENTITY, oldEntity, entity));
      }
    }
    return entity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entity basicGetEntity()
  {
    return entity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEntity(Entity newEntity)
  {
    Entity oldEntity = entity;
    entity = newEntity;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.ENTITY_TYPE__ENTITY, oldEntity, entity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CommonFieldType getCommonFieldType()
  {
    return commonFieldType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCommonFieldType(CommonFieldType newCommonFieldType)
  {
    CommonFieldType oldCommonFieldType = commonFieldType;
    commonFieldType = newCommonFieldType == null ? COMMON_FIELD_TYPE_EDEFAULT : newCommonFieldType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.ENTITY_TYPE__COMMON_FIELD_TYPE, oldCommonFieldType, commonFieldType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ComprasPackage.ENTITY_TYPE__ENTITY:
        if (resolve) return getEntity();
        return basicGetEntity();
      case ComprasPackage.ENTITY_TYPE__COMMON_FIELD_TYPE:
        return getCommonFieldType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ComprasPackage.ENTITY_TYPE__ENTITY:
        setEntity((Entity)newValue);
        return;
      case ComprasPackage.ENTITY_TYPE__COMMON_FIELD_TYPE:
        setCommonFieldType((CommonFieldType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ComprasPackage.ENTITY_TYPE__ENTITY:
        setEntity((Entity)null);
        return;
      case ComprasPackage.ENTITY_TYPE__COMMON_FIELD_TYPE:
        setCommonFieldType(COMMON_FIELD_TYPE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ComprasPackage.ENTITY_TYPE__ENTITY:
        return entity != null;
      case ComprasPackage.ENTITY_TYPE__COMMON_FIELD_TYPE:
        return commonFieldType != COMMON_FIELD_TYPE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (commonFieldType: ");
    result.append(commonFieldType);
    result.append(')');
    return result.toString();
  }

} //EntityTypeImpl
