/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.compras.compras.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.compras.compras.ComprasPackage;
import org.xtext.example.compras.compras.FuncViewGridAction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Func View Grid Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FuncViewGridActionImpl extends FunctionalityActionTypeImpl implements FuncViewGridAction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FuncViewGridActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ComprasPackage.Literals.FUNC_VIEW_GRID_ACTION;
  }

} //FuncViewGridActionImpl
