/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.compras.compras.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.compras.compras.ComprasPackage;
import org.xtext.example.compras.compras.FuncDeleteAction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Func Delete Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FuncDeleteActionImpl extends FunctionalityActionTypeImpl implements FuncDeleteAction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FuncDeleteActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ComprasPackage.Literals.FUNC_DELETE_ACTION;
  }

} //FuncDeleteActionImpl
