/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.compras.compras.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.compras.compras.ComprasPackage;
import org.xtext.example.compras.compras.FuncViewDropDownAction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Func View Drop Down Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FuncViewDropDownActionImpl extends FunctionalityActionTypeImpl implements FuncViewDropDownAction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FuncViewDropDownActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ComprasPackage.Literals.FUNC_VIEW_DROP_DOWN_ACTION;
  }

} //FuncViewDropDownActionImpl
