/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.compras.compras.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.compras.compras.ComprasPackage;
import org.xtext.example.compras.compras.ControllerSegmentLayer;
import org.xtext.example.compras.compras.PresentationLayer;
import org.xtext.example.compras.compras.ScriptSegmentLayer;
import org.xtext.example.compras.compras.ViewSegmentLayer;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Presentation Layer</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.compras.compras.impl.PresentationLayerImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.PresentationLayerImpl#getControllerSegmentLayer <em>Controller Segment Layer</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.PresentationLayerImpl#getViewSegmentLayer <em>View Segment Layer</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.PresentationLayerImpl#getScriptegmentLayer <em>Scriptegment Layer</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PresentationLayerImpl extends MinimalEObjectImpl.Container implements PresentationLayer
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getControllerSegmentLayer() <em>Controller Segment Layer</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getControllerSegmentLayer()
   * @generated
   * @ordered
   */
  protected ControllerSegmentLayer controllerSegmentLayer;

  /**
   * The cached value of the '{@link #getViewSegmentLayer() <em>View Segment Layer</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getViewSegmentLayer()
   * @generated
   * @ordered
   */
  protected ViewSegmentLayer viewSegmentLayer;

  /**
   * The cached value of the '{@link #getScriptegmentLayer() <em>Scriptegment Layer</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getScriptegmentLayer()
   * @generated
   * @ordered
   */
  protected ScriptSegmentLayer scriptegmentLayer;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PresentationLayerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ComprasPackage.Literals.PRESENTATION_LAYER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.PRESENTATION_LAYER__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ControllerSegmentLayer getControllerSegmentLayer()
  {
    return controllerSegmentLayer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetControllerSegmentLayer(ControllerSegmentLayer newControllerSegmentLayer, NotificationChain msgs)
  {
    ControllerSegmentLayer oldControllerSegmentLayer = controllerSegmentLayer;
    controllerSegmentLayer = newControllerSegmentLayer;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ComprasPackage.PRESENTATION_LAYER__CONTROLLER_SEGMENT_LAYER, oldControllerSegmentLayer, newControllerSegmentLayer);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setControllerSegmentLayer(ControllerSegmentLayer newControllerSegmentLayer)
  {
    if (newControllerSegmentLayer != controllerSegmentLayer)
    {
      NotificationChain msgs = null;
      if (controllerSegmentLayer != null)
        msgs = ((InternalEObject)controllerSegmentLayer).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ComprasPackage.PRESENTATION_LAYER__CONTROLLER_SEGMENT_LAYER, null, msgs);
      if (newControllerSegmentLayer != null)
        msgs = ((InternalEObject)newControllerSegmentLayer).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ComprasPackage.PRESENTATION_LAYER__CONTROLLER_SEGMENT_LAYER, null, msgs);
      msgs = basicSetControllerSegmentLayer(newControllerSegmentLayer, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.PRESENTATION_LAYER__CONTROLLER_SEGMENT_LAYER, newControllerSegmentLayer, newControllerSegmentLayer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ViewSegmentLayer getViewSegmentLayer()
  {
    return viewSegmentLayer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetViewSegmentLayer(ViewSegmentLayer newViewSegmentLayer, NotificationChain msgs)
  {
    ViewSegmentLayer oldViewSegmentLayer = viewSegmentLayer;
    viewSegmentLayer = newViewSegmentLayer;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ComprasPackage.PRESENTATION_LAYER__VIEW_SEGMENT_LAYER, oldViewSegmentLayer, newViewSegmentLayer);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setViewSegmentLayer(ViewSegmentLayer newViewSegmentLayer)
  {
    if (newViewSegmentLayer != viewSegmentLayer)
    {
      NotificationChain msgs = null;
      if (viewSegmentLayer != null)
        msgs = ((InternalEObject)viewSegmentLayer).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ComprasPackage.PRESENTATION_LAYER__VIEW_SEGMENT_LAYER, null, msgs);
      if (newViewSegmentLayer != null)
        msgs = ((InternalEObject)newViewSegmentLayer).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ComprasPackage.PRESENTATION_LAYER__VIEW_SEGMENT_LAYER, null, msgs);
      msgs = basicSetViewSegmentLayer(newViewSegmentLayer, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.PRESENTATION_LAYER__VIEW_SEGMENT_LAYER, newViewSegmentLayer, newViewSegmentLayer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ScriptSegmentLayer getScriptegmentLayer()
  {
    return scriptegmentLayer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetScriptegmentLayer(ScriptSegmentLayer newScriptegmentLayer, NotificationChain msgs)
  {
    ScriptSegmentLayer oldScriptegmentLayer = scriptegmentLayer;
    scriptegmentLayer = newScriptegmentLayer;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ComprasPackage.PRESENTATION_LAYER__SCRIPTEGMENT_LAYER, oldScriptegmentLayer, newScriptegmentLayer);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setScriptegmentLayer(ScriptSegmentLayer newScriptegmentLayer)
  {
    if (newScriptegmentLayer != scriptegmentLayer)
    {
      NotificationChain msgs = null;
      if (scriptegmentLayer != null)
        msgs = ((InternalEObject)scriptegmentLayer).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ComprasPackage.PRESENTATION_LAYER__SCRIPTEGMENT_LAYER, null, msgs);
      if (newScriptegmentLayer != null)
        msgs = ((InternalEObject)newScriptegmentLayer).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ComprasPackage.PRESENTATION_LAYER__SCRIPTEGMENT_LAYER, null, msgs);
      msgs = basicSetScriptegmentLayer(newScriptegmentLayer, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.PRESENTATION_LAYER__SCRIPTEGMENT_LAYER, newScriptegmentLayer, newScriptegmentLayer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ComprasPackage.PRESENTATION_LAYER__CONTROLLER_SEGMENT_LAYER:
        return basicSetControllerSegmentLayer(null, msgs);
      case ComprasPackage.PRESENTATION_LAYER__VIEW_SEGMENT_LAYER:
        return basicSetViewSegmentLayer(null, msgs);
      case ComprasPackage.PRESENTATION_LAYER__SCRIPTEGMENT_LAYER:
        return basicSetScriptegmentLayer(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ComprasPackage.PRESENTATION_LAYER__NAME:
        return getName();
      case ComprasPackage.PRESENTATION_LAYER__CONTROLLER_SEGMENT_LAYER:
        return getControllerSegmentLayer();
      case ComprasPackage.PRESENTATION_LAYER__VIEW_SEGMENT_LAYER:
        return getViewSegmentLayer();
      case ComprasPackage.PRESENTATION_LAYER__SCRIPTEGMENT_LAYER:
        return getScriptegmentLayer();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ComprasPackage.PRESENTATION_LAYER__NAME:
        setName((String)newValue);
        return;
      case ComprasPackage.PRESENTATION_LAYER__CONTROLLER_SEGMENT_LAYER:
        setControllerSegmentLayer((ControllerSegmentLayer)newValue);
        return;
      case ComprasPackage.PRESENTATION_LAYER__VIEW_SEGMENT_LAYER:
        setViewSegmentLayer((ViewSegmentLayer)newValue);
        return;
      case ComprasPackage.PRESENTATION_LAYER__SCRIPTEGMENT_LAYER:
        setScriptegmentLayer((ScriptSegmentLayer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ComprasPackage.PRESENTATION_LAYER__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ComprasPackage.PRESENTATION_LAYER__CONTROLLER_SEGMENT_LAYER:
        setControllerSegmentLayer((ControllerSegmentLayer)null);
        return;
      case ComprasPackage.PRESENTATION_LAYER__VIEW_SEGMENT_LAYER:
        setViewSegmentLayer((ViewSegmentLayer)null);
        return;
      case ComprasPackage.PRESENTATION_LAYER__SCRIPTEGMENT_LAYER:
        setScriptegmentLayer((ScriptSegmentLayer)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ComprasPackage.PRESENTATION_LAYER__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ComprasPackage.PRESENTATION_LAYER__CONTROLLER_SEGMENT_LAYER:
        return controllerSegmentLayer != null;
      case ComprasPackage.PRESENTATION_LAYER__VIEW_SEGMENT_LAYER:
        return viewSegmentLayer != null;
      case ComprasPackage.PRESENTATION_LAYER__SCRIPTEGMENT_LAYER:
        return scriptegmentLayer != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //PresentationLayerImpl
