/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.compras.compras.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.compras.compras.BusinessLayer;
import org.xtext.example.compras.compras.CommonLayer;
import org.xtext.example.compras.compras.ComprasPackage;
import org.xtext.example.compras.compras.DataAccessLayer;
import org.xtext.example.compras.compras.PresentationLayer;
import org.xtext.example.compras.compras.Relations;
import org.xtext.example.compras.compras.RelationsType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Relations</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.compras.compras.impl.RelationsImpl#getSourceLayer1 <em>Source Layer1</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.RelationsImpl#getRelationsType1 <em>Relations Type1</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.RelationsImpl#getTargetLayer1 <em>Target Layer1</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.RelationsImpl#getSourceLayer2 <em>Source Layer2</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.RelationsImpl#getRelationsType2 <em>Relations Type2</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.RelationsImpl#getTargetLayer2 <em>Target Layer2</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.RelationsImpl#getSourceLayer3 <em>Source Layer3</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.RelationsImpl#getRelationsType3 <em>Relations Type3</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.RelationsImpl#getTargetLayer3 <em>Target Layer3</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.RelationsImpl#getSourceLayer4 <em>Source Layer4</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.RelationsImpl#getRelationsType4 <em>Relations Type4</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.RelationsImpl#getTargetLayer4 <em>Target Layer4</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.RelationsImpl#getSourceLayer5 <em>Source Layer5</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.RelationsImpl#getRelationsType5 <em>Relations Type5</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.impl.RelationsImpl#getTargetLayer5 <em>Target Layer5</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RelationsImpl extends MinimalEObjectImpl.Container implements Relations
{
  /**
   * The cached value of the '{@link #getSourceLayer1() <em>Source Layer1</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourceLayer1()
   * @generated
   * @ordered
   */
  protected PresentationLayer sourceLayer1;

  /**
   * The default value of the '{@link #getRelationsType1() <em>Relations Type1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelationsType1()
   * @generated
   * @ordered
   */
  protected static final RelationsType RELATIONS_TYPE1_EDEFAULT = RelationsType.ALLOWED_TO_USE;

  /**
   * The cached value of the '{@link #getRelationsType1() <em>Relations Type1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelationsType1()
   * @generated
   * @ordered
   */
  protected RelationsType relationsType1 = RELATIONS_TYPE1_EDEFAULT;

  /**
   * The cached value of the '{@link #getTargetLayer1() <em>Target Layer1</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTargetLayer1()
   * @generated
   * @ordered
   */
  protected BusinessLayer targetLayer1;

  /**
   * The cached value of the '{@link #getSourceLayer2() <em>Source Layer2</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourceLayer2()
   * @generated
   * @ordered
   */
  protected BusinessLayer sourceLayer2;

  /**
   * The default value of the '{@link #getRelationsType2() <em>Relations Type2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelationsType2()
   * @generated
   * @ordered
   */
  protected static final RelationsType RELATIONS_TYPE2_EDEFAULT = RelationsType.ALLOWED_TO_USE;

  /**
   * The cached value of the '{@link #getRelationsType2() <em>Relations Type2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelationsType2()
   * @generated
   * @ordered
   */
  protected RelationsType relationsType2 = RELATIONS_TYPE2_EDEFAULT;

  /**
   * The cached value of the '{@link #getTargetLayer2() <em>Target Layer2</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTargetLayer2()
   * @generated
   * @ordered
   */
  protected DataAccessLayer targetLayer2;

  /**
   * The cached value of the '{@link #getSourceLayer3() <em>Source Layer3</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourceLayer3()
   * @generated
   * @ordered
   */
  protected DataAccessLayer sourceLayer3;

  /**
   * The default value of the '{@link #getRelationsType3() <em>Relations Type3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelationsType3()
   * @generated
   * @ordered
   */
  protected static final RelationsType RELATIONS_TYPE3_EDEFAULT = RelationsType.ALLOWED_TO_USE;

  /**
   * The cached value of the '{@link #getRelationsType3() <em>Relations Type3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelationsType3()
   * @generated
   * @ordered
   */
  protected RelationsType relationsType3 = RELATIONS_TYPE3_EDEFAULT;

  /**
   * The cached value of the '{@link #getTargetLayer3() <em>Target Layer3</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTargetLayer3()
   * @generated
   * @ordered
   */
  protected CommonLayer targetLayer3;

  /**
   * The cached value of the '{@link #getSourceLayer4() <em>Source Layer4</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourceLayer4()
   * @generated
   * @ordered
   */
  protected PresentationLayer sourceLayer4;

  /**
   * The default value of the '{@link #getRelationsType4() <em>Relations Type4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelationsType4()
   * @generated
   * @ordered
   */
  protected static final RelationsType RELATIONS_TYPE4_EDEFAULT = RelationsType.ALLOWED_TO_USE;

  /**
   * The cached value of the '{@link #getRelationsType4() <em>Relations Type4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelationsType4()
   * @generated
   * @ordered
   */
  protected RelationsType relationsType4 = RELATIONS_TYPE4_EDEFAULT;

  /**
   * The cached value of the '{@link #getTargetLayer4() <em>Target Layer4</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTargetLayer4()
   * @generated
   * @ordered
   */
  protected CommonLayer targetLayer4;

  /**
   * The cached value of the '{@link #getSourceLayer5() <em>Source Layer5</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourceLayer5()
   * @generated
   * @ordered
   */
  protected BusinessLayer sourceLayer5;

  /**
   * The default value of the '{@link #getRelationsType5() <em>Relations Type5</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelationsType5()
   * @generated
   * @ordered
   */
  protected static final RelationsType RELATIONS_TYPE5_EDEFAULT = RelationsType.ALLOWED_TO_USE;

  /**
   * The cached value of the '{@link #getRelationsType5() <em>Relations Type5</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRelationsType5()
   * @generated
   * @ordered
   */
  protected RelationsType relationsType5 = RELATIONS_TYPE5_EDEFAULT;

  /**
   * The cached value of the '{@link #getTargetLayer5() <em>Target Layer5</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTargetLayer5()
   * @generated
   * @ordered
   */
  protected CommonLayer targetLayer5;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RelationsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ComprasPackage.Literals.RELATIONS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PresentationLayer getSourceLayer1()
  {
    if (sourceLayer1 != null && sourceLayer1.eIsProxy())
    {
      InternalEObject oldSourceLayer1 = (InternalEObject)sourceLayer1;
      sourceLayer1 = (PresentationLayer)eResolveProxy(oldSourceLayer1);
      if (sourceLayer1 != oldSourceLayer1)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ComprasPackage.RELATIONS__SOURCE_LAYER1, oldSourceLayer1, sourceLayer1));
      }
    }
    return sourceLayer1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PresentationLayer basicGetSourceLayer1()
  {
    return sourceLayer1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSourceLayer1(PresentationLayer newSourceLayer1)
  {
    PresentationLayer oldSourceLayer1 = sourceLayer1;
    sourceLayer1 = newSourceLayer1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.RELATIONS__SOURCE_LAYER1, oldSourceLayer1, sourceLayer1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RelationsType getRelationsType1()
  {
    return relationsType1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRelationsType1(RelationsType newRelationsType1)
  {
    RelationsType oldRelationsType1 = relationsType1;
    relationsType1 = newRelationsType1 == null ? RELATIONS_TYPE1_EDEFAULT : newRelationsType1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.RELATIONS__RELATIONS_TYPE1, oldRelationsType1, relationsType1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BusinessLayer getTargetLayer1()
  {
    if (targetLayer1 != null && targetLayer1.eIsProxy())
    {
      InternalEObject oldTargetLayer1 = (InternalEObject)targetLayer1;
      targetLayer1 = (BusinessLayer)eResolveProxy(oldTargetLayer1);
      if (targetLayer1 != oldTargetLayer1)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ComprasPackage.RELATIONS__TARGET_LAYER1, oldTargetLayer1, targetLayer1));
      }
    }
    return targetLayer1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BusinessLayer basicGetTargetLayer1()
  {
    return targetLayer1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTargetLayer1(BusinessLayer newTargetLayer1)
  {
    BusinessLayer oldTargetLayer1 = targetLayer1;
    targetLayer1 = newTargetLayer1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.RELATIONS__TARGET_LAYER1, oldTargetLayer1, targetLayer1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BusinessLayer getSourceLayer2()
  {
    if (sourceLayer2 != null && sourceLayer2.eIsProxy())
    {
      InternalEObject oldSourceLayer2 = (InternalEObject)sourceLayer2;
      sourceLayer2 = (BusinessLayer)eResolveProxy(oldSourceLayer2);
      if (sourceLayer2 != oldSourceLayer2)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ComprasPackage.RELATIONS__SOURCE_LAYER2, oldSourceLayer2, sourceLayer2));
      }
    }
    return sourceLayer2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BusinessLayer basicGetSourceLayer2()
  {
    return sourceLayer2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSourceLayer2(BusinessLayer newSourceLayer2)
  {
    BusinessLayer oldSourceLayer2 = sourceLayer2;
    sourceLayer2 = newSourceLayer2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.RELATIONS__SOURCE_LAYER2, oldSourceLayer2, sourceLayer2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RelationsType getRelationsType2()
  {
    return relationsType2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRelationsType2(RelationsType newRelationsType2)
  {
    RelationsType oldRelationsType2 = relationsType2;
    relationsType2 = newRelationsType2 == null ? RELATIONS_TYPE2_EDEFAULT : newRelationsType2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.RELATIONS__RELATIONS_TYPE2, oldRelationsType2, relationsType2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DataAccessLayer getTargetLayer2()
  {
    if (targetLayer2 != null && targetLayer2.eIsProxy())
    {
      InternalEObject oldTargetLayer2 = (InternalEObject)targetLayer2;
      targetLayer2 = (DataAccessLayer)eResolveProxy(oldTargetLayer2);
      if (targetLayer2 != oldTargetLayer2)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ComprasPackage.RELATIONS__TARGET_LAYER2, oldTargetLayer2, targetLayer2));
      }
    }
    return targetLayer2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataAccessLayer basicGetTargetLayer2()
  {
    return targetLayer2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTargetLayer2(DataAccessLayer newTargetLayer2)
  {
    DataAccessLayer oldTargetLayer2 = targetLayer2;
    targetLayer2 = newTargetLayer2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.RELATIONS__TARGET_LAYER2, oldTargetLayer2, targetLayer2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DataAccessLayer getSourceLayer3()
  {
    if (sourceLayer3 != null && sourceLayer3.eIsProxy())
    {
      InternalEObject oldSourceLayer3 = (InternalEObject)sourceLayer3;
      sourceLayer3 = (DataAccessLayer)eResolveProxy(oldSourceLayer3);
      if (sourceLayer3 != oldSourceLayer3)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ComprasPackage.RELATIONS__SOURCE_LAYER3, oldSourceLayer3, sourceLayer3));
      }
    }
    return sourceLayer3;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataAccessLayer basicGetSourceLayer3()
  {
    return sourceLayer3;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSourceLayer3(DataAccessLayer newSourceLayer3)
  {
    DataAccessLayer oldSourceLayer3 = sourceLayer3;
    sourceLayer3 = newSourceLayer3;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.RELATIONS__SOURCE_LAYER3, oldSourceLayer3, sourceLayer3));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RelationsType getRelationsType3()
  {
    return relationsType3;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRelationsType3(RelationsType newRelationsType3)
  {
    RelationsType oldRelationsType3 = relationsType3;
    relationsType3 = newRelationsType3 == null ? RELATIONS_TYPE3_EDEFAULT : newRelationsType3;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.RELATIONS__RELATIONS_TYPE3, oldRelationsType3, relationsType3));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CommonLayer getTargetLayer3()
  {
    if (targetLayer3 != null && targetLayer3.eIsProxy())
    {
      InternalEObject oldTargetLayer3 = (InternalEObject)targetLayer3;
      targetLayer3 = (CommonLayer)eResolveProxy(oldTargetLayer3);
      if (targetLayer3 != oldTargetLayer3)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ComprasPackage.RELATIONS__TARGET_LAYER3, oldTargetLayer3, targetLayer3));
      }
    }
    return targetLayer3;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CommonLayer basicGetTargetLayer3()
  {
    return targetLayer3;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTargetLayer3(CommonLayer newTargetLayer3)
  {
    CommonLayer oldTargetLayer3 = targetLayer3;
    targetLayer3 = newTargetLayer3;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.RELATIONS__TARGET_LAYER3, oldTargetLayer3, targetLayer3));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PresentationLayer getSourceLayer4()
  {
    if (sourceLayer4 != null && sourceLayer4.eIsProxy())
    {
      InternalEObject oldSourceLayer4 = (InternalEObject)sourceLayer4;
      sourceLayer4 = (PresentationLayer)eResolveProxy(oldSourceLayer4);
      if (sourceLayer4 != oldSourceLayer4)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ComprasPackage.RELATIONS__SOURCE_LAYER4, oldSourceLayer4, sourceLayer4));
      }
    }
    return sourceLayer4;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PresentationLayer basicGetSourceLayer4()
  {
    return sourceLayer4;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSourceLayer4(PresentationLayer newSourceLayer4)
  {
    PresentationLayer oldSourceLayer4 = sourceLayer4;
    sourceLayer4 = newSourceLayer4;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.RELATIONS__SOURCE_LAYER4, oldSourceLayer4, sourceLayer4));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RelationsType getRelationsType4()
  {
    return relationsType4;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRelationsType4(RelationsType newRelationsType4)
  {
    RelationsType oldRelationsType4 = relationsType4;
    relationsType4 = newRelationsType4 == null ? RELATIONS_TYPE4_EDEFAULT : newRelationsType4;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.RELATIONS__RELATIONS_TYPE4, oldRelationsType4, relationsType4));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CommonLayer getTargetLayer4()
  {
    if (targetLayer4 != null && targetLayer4.eIsProxy())
    {
      InternalEObject oldTargetLayer4 = (InternalEObject)targetLayer4;
      targetLayer4 = (CommonLayer)eResolveProxy(oldTargetLayer4);
      if (targetLayer4 != oldTargetLayer4)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ComprasPackage.RELATIONS__TARGET_LAYER4, oldTargetLayer4, targetLayer4));
      }
    }
    return targetLayer4;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CommonLayer basicGetTargetLayer4()
  {
    return targetLayer4;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTargetLayer4(CommonLayer newTargetLayer4)
  {
    CommonLayer oldTargetLayer4 = targetLayer4;
    targetLayer4 = newTargetLayer4;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.RELATIONS__TARGET_LAYER4, oldTargetLayer4, targetLayer4));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BusinessLayer getSourceLayer5()
  {
    if (sourceLayer5 != null && sourceLayer5.eIsProxy())
    {
      InternalEObject oldSourceLayer5 = (InternalEObject)sourceLayer5;
      sourceLayer5 = (BusinessLayer)eResolveProxy(oldSourceLayer5);
      if (sourceLayer5 != oldSourceLayer5)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ComprasPackage.RELATIONS__SOURCE_LAYER5, oldSourceLayer5, sourceLayer5));
      }
    }
    return sourceLayer5;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BusinessLayer basicGetSourceLayer5()
  {
    return sourceLayer5;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSourceLayer5(BusinessLayer newSourceLayer5)
  {
    BusinessLayer oldSourceLayer5 = sourceLayer5;
    sourceLayer5 = newSourceLayer5;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.RELATIONS__SOURCE_LAYER5, oldSourceLayer5, sourceLayer5));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RelationsType getRelationsType5()
  {
    return relationsType5;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRelationsType5(RelationsType newRelationsType5)
  {
    RelationsType oldRelationsType5 = relationsType5;
    relationsType5 = newRelationsType5 == null ? RELATIONS_TYPE5_EDEFAULT : newRelationsType5;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.RELATIONS__RELATIONS_TYPE5, oldRelationsType5, relationsType5));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CommonLayer getTargetLayer5()
  {
    if (targetLayer5 != null && targetLayer5.eIsProxy())
    {
      InternalEObject oldTargetLayer5 = (InternalEObject)targetLayer5;
      targetLayer5 = (CommonLayer)eResolveProxy(oldTargetLayer5);
      if (targetLayer5 != oldTargetLayer5)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ComprasPackage.RELATIONS__TARGET_LAYER5, oldTargetLayer5, targetLayer5));
      }
    }
    return targetLayer5;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CommonLayer basicGetTargetLayer5()
  {
    return targetLayer5;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTargetLayer5(CommonLayer newTargetLayer5)
  {
    CommonLayer oldTargetLayer5 = targetLayer5;
    targetLayer5 = newTargetLayer5;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.RELATIONS__TARGET_LAYER5, oldTargetLayer5, targetLayer5));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ComprasPackage.RELATIONS__SOURCE_LAYER1:
        if (resolve) return getSourceLayer1();
        return basicGetSourceLayer1();
      case ComprasPackage.RELATIONS__RELATIONS_TYPE1:
        return getRelationsType1();
      case ComprasPackage.RELATIONS__TARGET_LAYER1:
        if (resolve) return getTargetLayer1();
        return basicGetTargetLayer1();
      case ComprasPackage.RELATIONS__SOURCE_LAYER2:
        if (resolve) return getSourceLayer2();
        return basicGetSourceLayer2();
      case ComprasPackage.RELATIONS__RELATIONS_TYPE2:
        return getRelationsType2();
      case ComprasPackage.RELATIONS__TARGET_LAYER2:
        if (resolve) return getTargetLayer2();
        return basicGetTargetLayer2();
      case ComprasPackage.RELATIONS__SOURCE_LAYER3:
        if (resolve) return getSourceLayer3();
        return basicGetSourceLayer3();
      case ComprasPackage.RELATIONS__RELATIONS_TYPE3:
        return getRelationsType3();
      case ComprasPackage.RELATIONS__TARGET_LAYER3:
        if (resolve) return getTargetLayer3();
        return basicGetTargetLayer3();
      case ComprasPackage.RELATIONS__SOURCE_LAYER4:
        if (resolve) return getSourceLayer4();
        return basicGetSourceLayer4();
      case ComprasPackage.RELATIONS__RELATIONS_TYPE4:
        return getRelationsType4();
      case ComprasPackage.RELATIONS__TARGET_LAYER4:
        if (resolve) return getTargetLayer4();
        return basicGetTargetLayer4();
      case ComprasPackage.RELATIONS__SOURCE_LAYER5:
        if (resolve) return getSourceLayer5();
        return basicGetSourceLayer5();
      case ComprasPackage.RELATIONS__RELATIONS_TYPE5:
        return getRelationsType5();
      case ComprasPackage.RELATIONS__TARGET_LAYER5:
        if (resolve) return getTargetLayer5();
        return basicGetTargetLayer5();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ComprasPackage.RELATIONS__SOURCE_LAYER1:
        setSourceLayer1((PresentationLayer)newValue);
        return;
      case ComprasPackage.RELATIONS__RELATIONS_TYPE1:
        setRelationsType1((RelationsType)newValue);
        return;
      case ComprasPackage.RELATIONS__TARGET_LAYER1:
        setTargetLayer1((BusinessLayer)newValue);
        return;
      case ComprasPackage.RELATIONS__SOURCE_LAYER2:
        setSourceLayer2((BusinessLayer)newValue);
        return;
      case ComprasPackage.RELATIONS__RELATIONS_TYPE2:
        setRelationsType2((RelationsType)newValue);
        return;
      case ComprasPackage.RELATIONS__TARGET_LAYER2:
        setTargetLayer2((DataAccessLayer)newValue);
        return;
      case ComprasPackage.RELATIONS__SOURCE_LAYER3:
        setSourceLayer3((DataAccessLayer)newValue);
        return;
      case ComprasPackage.RELATIONS__RELATIONS_TYPE3:
        setRelationsType3((RelationsType)newValue);
        return;
      case ComprasPackage.RELATIONS__TARGET_LAYER3:
        setTargetLayer3((CommonLayer)newValue);
        return;
      case ComprasPackage.RELATIONS__SOURCE_LAYER4:
        setSourceLayer4((PresentationLayer)newValue);
        return;
      case ComprasPackage.RELATIONS__RELATIONS_TYPE4:
        setRelationsType4((RelationsType)newValue);
        return;
      case ComprasPackage.RELATIONS__TARGET_LAYER4:
        setTargetLayer4((CommonLayer)newValue);
        return;
      case ComprasPackage.RELATIONS__SOURCE_LAYER5:
        setSourceLayer5((BusinessLayer)newValue);
        return;
      case ComprasPackage.RELATIONS__RELATIONS_TYPE5:
        setRelationsType5((RelationsType)newValue);
        return;
      case ComprasPackage.RELATIONS__TARGET_LAYER5:
        setTargetLayer5((CommonLayer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ComprasPackage.RELATIONS__SOURCE_LAYER1:
        setSourceLayer1((PresentationLayer)null);
        return;
      case ComprasPackage.RELATIONS__RELATIONS_TYPE1:
        setRelationsType1(RELATIONS_TYPE1_EDEFAULT);
        return;
      case ComprasPackage.RELATIONS__TARGET_LAYER1:
        setTargetLayer1((BusinessLayer)null);
        return;
      case ComprasPackage.RELATIONS__SOURCE_LAYER2:
        setSourceLayer2((BusinessLayer)null);
        return;
      case ComprasPackage.RELATIONS__RELATIONS_TYPE2:
        setRelationsType2(RELATIONS_TYPE2_EDEFAULT);
        return;
      case ComprasPackage.RELATIONS__TARGET_LAYER2:
        setTargetLayer2((DataAccessLayer)null);
        return;
      case ComprasPackage.RELATIONS__SOURCE_LAYER3:
        setSourceLayer3((DataAccessLayer)null);
        return;
      case ComprasPackage.RELATIONS__RELATIONS_TYPE3:
        setRelationsType3(RELATIONS_TYPE3_EDEFAULT);
        return;
      case ComprasPackage.RELATIONS__TARGET_LAYER3:
        setTargetLayer3((CommonLayer)null);
        return;
      case ComprasPackage.RELATIONS__SOURCE_LAYER4:
        setSourceLayer4((PresentationLayer)null);
        return;
      case ComprasPackage.RELATIONS__RELATIONS_TYPE4:
        setRelationsType4(RELATIONS_TYPE4_EDEFAULT);
        return;
      case ComprasPackage.RELATIONS__TARGET_LAYER4:
        setTargetLayer4((CommonLayer)null);
        return;
      case ComprasPackage.RELATIONS__SOURCE_LAYER5:
        setSourceLayer5((BusinessLayer)null);
        return;
      case ComprasPackage.RELATIONS__RELATIONS_TYPE5:
        setRelationsType5(RELATIONS_TYPE5_EDEFAULT);
        return;
      case ComprasPackage.RELATIONS__TARGET_LAYER5:
        setTargetLayer5((CommonLayer)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ComprasPackage.RELATIONS__SOURCE_LAYER1:
        return sourceLayer1 != null;
      case ComprasPackage.RELATIONS__RELATIONS_TYPE1:
        return relationsType1 != RELATIONS_TYPE1_EDEFAULT;
      case ComprasPackage.RELATIONS__TARGET_LAYER1:
        return targetLayer1 != null;
      case ComprasPackage.RELATIONS__SOURCE_LAYER2:
        return sourceLayer2 != null;
      case ComprasPackage.RELATIONS__RELATIONS_TYPE2:
        return relationsType2 != RELATIONS_TYPE2_EDEFAULT;
      case ComprasPackage.RELATIONS__TARGET_LAYER2:
        return targetLayer2 != null;
      case ComprasPackage.RELATIONS__SOURCE_LAYER3:
        return sourceLayer3 != null;
      case ComprasPackage.RELATIONS__RELATIONS_TYPE3:
        return relationsType3 != RELATIONS_TYPE3_EDEFAULT;
      case ComprasPackage.RELATIONS__TARGET_LAYER3:
        return targetLayer3 != null;
      case ComprasPackage.RELATIONS__SOURCE_LAYER4:
        return sourceLayer4 != null;
      case ComprasPackage.RELATIONS__RELATIONS_TYPE4:
        return relationsType4 != RELATIONS_TYPE4_EDEFAULT;
      case ComprasPackage.RELATIONS__TARGET_LAYER4:
        return targetLayer4 != null;
      case ComprasPackage.RELATIONS__SOURCE_LAYER5:
        return sourceLayer5 != null;
      case ComprasPackage.RELATIONS__RELATIONS_TYPE5:
        return relationsType5 != RELATIONS_TYPE5_EDEFAULT;
      case ComprasPackage.RELATIONS__TARGET_LAYER5:
        return targetLayer5 != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (relationsType1: ");
    result.append(relationsType1);
    result.append(", relationsType2: ");
    result.append(relationsType2);
    result.append(", relationsType3: ");
    result.append(relationsType3);
    result.append(", relationsType4: ");
    result.append(relationsType4);
    result.append(", relationsType5: ");
    result.append(relationsType5);
    result.append(')');
    return result.toString();
  }

} //RelationsImpl
