/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.compras.compras.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.compras.compras.ComprasPackage;
import org.xtext.example.compras.compras.Functionality;
import org.xtext.example.compras.compras.ScriptRef;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Script Ref</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.compras.compras.impl.ScriptRefImpl#getFunctionality <em>Functionality</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ScriptRefImpl extends MinimalEObjectImpl.Container implements ScriptRef
{
  /**
   * The cached value of the '{@link #getFunctionality() <em>Functionality</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunctionality()
   * @generated
   * @ordered
   */
  protected Functionality functionality;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ScriptRefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ComprasPackage.Literals.SCRIPT_REF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Functionality getFunctionality()
  {
    if (functionality != null && functionality.eIsProxy())
    {
      InternalEObject oldFunctionality = (InternalEObject)functionality;
      functionality = (Functionality)eResolveProxy(oldFunctionality);
      if (functionality != oldFunctionality)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ComprasPackage.SCRIPT_REF__FUNCTIONALITY, oldFunctionality, functionality));
      }
    }
    return functionality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Functionality basicGetFunctionality()
  {
    return functionality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFunctionality(Functionality newFunctionality)
  {
    Functionality oldFunctionality = functionality;
    functionality = newFunctionality;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComprasPackage.SCRIPT_REF__FUNCTIONALITY, oldFunctionality, functionality));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ComprasPackage.SCRIPT_REF__FUNCTIONALITY:
        if (resolve) return getFunctionality();
        return basicGetFunctionality();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ComprasPackage.SCRIPT_REF__FUNCTIONALITY:
        setFunctionality((Functionality)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ComprasPackage.SCRIPT_REF__FUNCTIONALITY:
        setFunctionality((Functionality)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ComprasPackage.SCRIPT_REF__FUNCTIONALITY:
        return functionality != null;
    }
    return super.eIsSet(featureID);
  }

} //ScriptRefImpl
