/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.compras.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.compras.ui.AbstractComprasUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ComprasUiModule extends AbstractComprasUiModule {
  public ComprasUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
