/*
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.compras.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.compras.ui.internal.ComprasActivator;

public class ComprasUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ComprasActivator.getInstance().getInjector("org.xtext.example.compras.Compras");
	}

}
