/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.compras.compras;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Func Edit Action</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.compras.compras.ComprasPackage#getFuncEditAction()
 * @model
 * @generated
 */
public interface FuncEditAction extends FunctionalityActionType
{
} // FuncEditAction
