/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.compras.compras;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Func View Grid Action</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.compras.compras.ComprasPackage#getFuncViewGridAction()
 * @model
 * @generated
 */
public interface FuncViewGridAction extends FunctionalityActionType
{
} // FuncViewGridAction
