/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.compras.compras;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Func Delete Action</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.compras.compras.ComprasPackage#getFuncDeleteAction()
 * @model
 * @generated
 */
public interface FuncDeleteAction extends FunctionalityActionType
{
} // FuncDeleteAction
