/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.compras.compras;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Module</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.compras.compras.Module#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.Module#getEntity <em>Entity</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.Module#getFunctionality <em>Functionality</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.compras.compras.ComprasPackage#getModule()
 * @model
 * @generated
 */
public interface Module extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.compras.compras.ComprasPackage#getModule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.compras.compras.Module#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Entity</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.compras.compras.Entity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' containment reference list.
   * @see org.xtext.example.compras.compras.ComprasPackage#getModule_Entity()
   * @model containment="true"
   * @generated
   */
  EList<Entity> getEntity();

  /**
   * Returns the value of the '<em><b>Functionality</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.compras.compras.Functionality}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Functionality</em>' containment reference list.
   * @see org.xtext.example.compras.compras.ComprasPackage#getModule_Functionality()
   * @model containment="true"
   * @generated
   */
  EList<Functionality> getFunctionality();

} // Module
