/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.compras.compras;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Module Tech</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.compras.compras.ModuleTech#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.ModuleTech#getPresentationLayer <em>Presentation Layer</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.ModuleTech#getControllerSegmentLayer <em>Controller Segment Layer</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.ModuleTech#getControllersRef <em>Controllers Ref</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.ModuleTech#getViewSegmentLayer <em>View Segment Layer</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.ModuleTech#getViewsRef <em>Views Ref</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.ModuleTech#getScriptSegmentLayer <em>Script Segment Layer</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.ModuleTech#getScriptRef <em>Script Ref</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.ModuleTech#getBusinessLayer <em>Business Layer</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.ModuleTech#getBusinessLayerRef <em>Business Layer Ref</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.ModuleTech#getDataAccessLayer <em>Data Access Layer</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.ModuleTech#getDataAccessLayerRef <em>Data Access Layer Ref</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.ModuleTech#getCommonLayer <em>Common Layer</em>}</li>
 *   <li>{@link org.xtext.example.compras.compras.ModuleTech#getCommonLayerRef <em>Common Layer Ref</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.compras.compras.ComprasPackage#getModuleTech()
 * @model
 * @generated
 */
public interface ModuleTech extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(org.xtext.example.compras.compras.Module)
   * @see org.xtext.example.compras.compras.ComprasPackage#getModuleTech_Name()
   * @model
   * @generated
   */
  org.xtext.example.compras.compras.Module getName();

  /**
   * Sets the value of the '{@link org.xtext.example.compras.compras.ModuleTech#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(org.xtext.example.compras.compras.Module value);

  /**
   * Returns the value of the '<em><b>Presentation Layer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Presentation Layer</em>' reference.
   * @see #setPresentationLayer(PresentationLayer)
   * @see org.xtext.example.compras.compras.ComprasPackage#getModuleTech_PresentationLayer()
   * @model
   * @generated
   */
  PresentationLayer getPresentationLayer();

  /**
   * Sets the value of the '{@link org.xtext.example.compras.compras.ModuleTech#getPresentationLayer <em>Presentation Layer</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Presentation Layer</em>' reference.
   * @see #getPresentationLayer()
   * @generated
   */
  void setPresentationLayer(PresentationLayer value);

  /**
   * Returns the value of the '<em><b>Controller Segment Layer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Controller Segment Layer</em>' reference.
   * @see #setControllerSegmentLayer(ControllerSegmentLayer)
   * @see org.xtext.example.compras.compras.ComprasPackage#getModuleTech_ControllerSegmentLayer()
   * @model
   * @generated
   */
  ControllerSegmentLayer getControllerSegmentLayer();

  /**
   * Sets the value of the '{@link org.xtext.example.compras.compras.ModuleTech#getControllerSegmentLayer <em>Controller Segment Layer</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Controller Segment Layer</em>' reference.
   * @see #getControllerSegmentLayer()
   * @generated
   */
  void setControllerSegmentLayer(ControllerSegmentLayer value);

  /**
   * Returns the value of the '<em><b>Controllers Ref</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.compras.compras.ControllersRef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Controllers Ref</em>' containment reference list.
   * @see org.xtext.example.compras.compras.ComprasPackage#getModuleTech_ControllersRef()
   * @model containment="true"
   * @generated
   */
  EList<ControllersRef> getControllersRef();

  /**
   * Returns the value of the '<em><b>View Segment Layer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>View Segment Layer</em>' reference.
   * @see #setViewSegmentLayer(ViewSegmentLayer)
   * @see org.xtext.example.compras.compras.ComprasPackage#getModuleTech_ViewSegmentLayer()
   * @model
   * @generated
   */
  ViewSegmentLayer getViewSegmentLayer();

  /**
   * Sets the value of the '{@link org.xtext.example.compras.compras.ModuleTech#getViewSegmentLayer <em>View Segment Layer</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>View Segment Layer</em>' reference.
   * @see #getViewSegmentLayer()
   * @generated
   */
  void setViewSegmentLayer(ViewSegmentLayer value);

  /**
   * Returns the value of the '<em><b>Views Ref</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.compras.compras.ViewsRef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Views Ref</em>' containment reference list.
   * @see org.xtext.example.compras.compras.ComprasPackage#getModuleTech_ViewsRef()
   * @model containment="true"
   * @generated
   */
  EList<ViewsRef> getViewsRef();

  /**
   * Returns the value of the '<em><b>Script Segment Layer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Script Segment Layer</em>' reference.
   * @see #setScriptSegmentLayer(ScriptSegmentLayer)
   * @see org.xtext.example.compras.compras.ComprasPackage#getModuleTech_ScriptSegmentLayer()
   * @model
   * @generated
   */
  ScriptSegmentLayer getScriptSegmentLayer();

  /**
   * Sets the value of the '{@link org.xtext.example.compras.compras.ModuleTech#getScriptSegmentLayer <em>Script Segment Layer</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Script Segment Layer</em>' reference.
   * @see #getScriptSegmentLayer()
   * @generated
   */
  void setScriptSegmentLayer(ScriptSegmentLayer value);

  /**
   * Returns the value of the '<em><b>Script Ref</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.compras.compras.ScriptRef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Script Ref</em>' containment reference list.
   * @see org.xtext.example.compras.compras.ComprasPackage#getModuleTech_ScriptRef()
   * @model containment="true"
   * @generated
   */
  EList<ScriptRef> getScriptRef();

  /**
   * Returns the value of the '<em><b>Business Layer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Business Layer</em>' reference.
   * @see #setBusinessLayer(BusinessLayer)
   * @see org.xtext.example.compras.compras.ComprasPackage#getModuleTech_BusinessLayer()
   * @model
   * @generated
   */
  BusinessLayer getBusinessLayer();

  /**
   * Sets the value of the '{@link org.xtext.example.compras.compras.ModuleTech#getBusinessLayer <em>Business Layer</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Business Layer</em>' reference.
   * @see #getBusinessLayer()
   * @generated
   */
  void setBusinessLayer(BusinessLayer value);

  /**
   * Returns the value of the '<em><b>Business Layer Ref</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.compras.compras.BusinessLayerRef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Business Layer Ref</em>' containment reference list.
   * @see org.xtext.example.compras.compras.ComprasPackage#getModuleTech_BusinessLayerRef()
   * @model containment="true"
   * @generated
   */
  EList<BusinessLayerRef> getBusinessLayerRef();

  /**
   * Returns the value of the '<em><b>Data Access Layer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Access Layer</em>' reference.
   * @see #setDataAccessLayer(DataAccessLayer)
   * @see org.xtext.example.compras.compras.ComprasPackage#getModuleTech_DataAccessLayer()
   * @model
   * @generated
   */
  DataAccessLayer getDataAccessLayer();

  /**
   * Sets the value of the '{@link org.xtext.example.compras.compras.ModuleTech#getDataAccessLayer <em>Data Access Layer</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Access Layer</em>' reference.
   * @see #getDataAccessLayer()
   * @generated
   */
  void setDataAccessLayer(DataAccessLayer value);

  /**
   * Returns the value of the '<em><b>Data Access Layer Ref</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.compras.compras.DataAccessLayerRef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Access Layer Ref</em>' containment reference list.
   * @see org.xtext.example.compras.compras.ComprasPackage#getModuleTech_DataAccessLayerRef()
   * @model containment="true"
   * @generated
   */
  EList<DataAccessLayerRef> getDataAccessLayerRef();

  /**
   * Returns the value of the '<em><b>Common Layer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Common Layer</em>' reference.
   * @see #setCommonLayer(CommonLayer)
   * @see org.xtext.example.compras.compras.ComprasPackage#getModuleTech_CommonLayer()
   * @model
   * @generated
   */
  CommonLayer getCommonLayer();

  /**
   * Sets the value of the '{@link org.xtext.example.compras.compras.ModuleTech#getCommonLayer <em>Common Layer</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Common Layer</em>' reference.
   * @see #getCommonLayer()
   * @generated
   */
  void setCommonLayer(CommonLayer value);

  /**
   * Returns the value of the '<em><b>Common Layer Ref</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.compras.compras.CommonLayerRef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Common Layer Ref</em>' containment reference list.
   * @see org.xtext.example.compras.compras.ComprasPackage#getModuleTech_CommonLayerRef()
   * @model containment="true"
   * @generated
   */
  EList<CommonLayerRef> getCommonLayerRef();

} // ModuleTech
