/*
 * generated by Xtext 2.17.0
 */
package org.xtext.example.compras.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ComprasProposalProvider extends AbstractComprasProposalProvider {
}
